apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
    tcp-route-sync: "true"
    http-route-sync: "true"
  name: nginx
spec:
  ports:
    - port: 80
  selector:
    app: nginx
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
